name: dom

on:
  schedule:
    - cron: '*/5 * * * *' # Her 5 dakikada bir çalıştırılır
  workflow_dispatch: # Manuel olarak da tetiklenebilir

jobs:
  check-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Kod deposunu çek
        uses: actions/checkout@v3

      - name: URL'yi kontrol et ve güncelle
        run: |
          FILE="test"
          URL=$(cat $FILE)
          BASE_URL="https://dizipal"
          NUMBER=$(echo $URL | grep -oP '\d+' | tail -1)

          # URL'nin çalışıp çalışmadığını kontrol et
          if ! curl -s --head "$URL" | grep "200 OK" > /dev/null; then
            echo "URL çalışmıyor, güncelleniyor..."
            NEW_NUMBER=$((NUMBER + 1))
            NEW_URL="${BASE_URL}${NEW_NUMBER}.com"

            # Dosyayı güncelle
            echo "$NEW_URL" > $FILE

            # Değişiklikleri commit et ve pushla
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add $FILE
            git commit -m "URL güncellendi: $NEW_URL"
            git push
          else
            echo "URL çalışıyor, işlem yapılmadı."
          fi
